"""
rag_pipeline.py
===============
Step 5 – The full end-to-end RAG pipeline for SystemVerilog Assertion generation.

Combines the embedding model, vector database, prompt builder, and 
cloud LLM connection into a single, efficient, unified interface. 
By maintaining these components in a stateful class, we avoid 
reloading models and indexes on every query.

Usage:
    from rag_pipeline import SVAGeneratorPipeline
    pipeline = SVAGeneratorPipeline()
    sva = pipeline.generate_assertions(my_rtl_code)
"""

import os
import sys

from dotenv import load_dotenv
from ollama import Client
from sentence_transformers import SentenceTransformer

from retriever import MODEL_NAME, load_index, retrieve
from prompt_builder import SYSTEM_PROMPT, build_prompt

# Ensure environment variables are loaded
load_dotenv()

OLLAMA_MODEL = "kimi-k2.5"

class SVAGeneratorPipeline:
    """
    End-to-End RAG Pipeline for SVA Generation.
    
    Holds in memory:
      - The local sentence-transformer embedding model
      - The local FAISS vector index & dataset records
      - The Ollama cloud API client
    """

    def __init__(self, top_k: int = 3):
        """Initializes all heavy components once."""
        print("[INIT] Setting up the SVA RAG Pipeline...")
        self.top_k = top_k

        # 1. Setup Local Embedding Model
        print(f"       Loading embedding model ({MODEL_NAME})...")
        self.embed_model = SentenceTransformer(MODEL_NAME)

        # 2. Setup Local Vector DB (FAISS)
        print("       Loading FAISS index and dataset records...")
        self.index, self.records = load_index()
        print(f"       --> Database ready ({self.index.ntotal:,} vectors).")

        # 3. Setup Cloud LLM Client
        print(f"       Initializing Ollama connection for '{OLLAMA_MODEL}'...")
        api_key = os.environ.get("OLLAMA_API_KEY")
        if not api_key:
            sys.exit(
                "[ERROR] OLLAMA_API_KEY environment variable is not set.\n"
                "Please add it to your .env file or export it."
            )
        self.client = Client(
            host="https://ollama.com",
            headers={"Authorization": f"Bearer {api_key}"},
        )
        print("[INIT] Pipeline ready.\n")


    def generate_assertions(
        self,
        rtl_code: str,
        clock_hint: str | None = None,
        synchronous_filter: str | None = None,
        stream: bool = True
    ) -> str:
        """
        Executes the full RAG pipeline for a given piece of RTL.

        Pipeline Steps:
            1. Retrieve top-k similar examples from FAISS.
            2. Build the few-shot prompt with the retrieved examples.
            3. Call Ollama (kimi-k2.5) to generate the SVA.

        Args:
            rtl_code:           The user's input code.
            clock_hint:         Optional string like 'posedge clk'.
            synchronous_filter: Set "True" or "False" to force retrieval
                                of sync/async examples only.
            stream:             Whether to live-print output to stdout.

        Returns:
            The raw property strings generated by the LLM.
        """
        
        # Step 1: Retrieval
        examples = retrieve(
            query_rtl=rtl_code,
            model=self.embed_model,
            index=self.index,
            records=self.records,
            top_k=self.top_k,
            filter_synchronous=synchronous_filter
        )

        # Step 2: Prompt Building
        prompt = build_prompt(
            query_rtl=rtl_code,
            retrieved_examples=examples,
            clock_hint=clock_hint
        )

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": prompt},
        ]

        # Step 3: Call LLM
        output_chunks = []
        if stream:
            for part in self.client.chat(OLLAMA_MODEL, messages=messages, stream=True):
                chunk = part["message"]["content"]
                print(chunk, end="", flush=True)
                output_chunks.append(chunk)
            print() # flush newline
        else:
            response = self.client.chat(OLLAMA_MODEL, messages=messages, stream=False)
            output = response["message"]["content"]
            output_chunks.append(output)

        return "".join(output_chunks)


# ─────────────────────────────────────────────────────────────
# PIPELINE DEMO / TEST
# ─────────────────────────────────────────────────────────────

def run_demo():
    print("==================================================================")
    print("  STEP 5: END-TO-END RAG PIPELINE DEMO")
    print("==================================================================")
    
    # Initialize only once!
    pipeline = SVAGeneratorPipeline(top_k=3)

    query_rtl = """\
always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        valid_out <= 1'b0;
        data_out  <= 8'h00;
    end else if (enable) begin
        valid_out <= 1'b1;
        data_out  <= data_in + offset;
    end else begin
        valid_out <= 1'b0;
    end
end\
"""

    print("RTL REQUEST:\n")
    print(query_rtl)
    print("\n------------------------------------------------------------------")
    print("GENERATING SVA (streaming)...\n")
    
    # Execute query
    assertions = pipeline.generate_assertions(
        rtl_code=query_rtl,
        clock_hint="posedge clk",
        synchronous_filter="True" 
    )

    print("\n==================================================================")


if __name__ == "__main__":
    run_demo()
